<?php

namespace app\admin\model;

use think\Model;

class CustomersPremises extends Model{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    //获取物流名称
    public function getPreLogIdAttr($vaule) {
        $model = new Logistics();
        $result = $model::get($vaule);
        return $result;
    }
}