<?php

namespace app\admin\model;

use think\Model;

class CustomersEvaluate extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}