<?php

namespace app\admin\model;

use think\Model;

class CustomersType extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected $pk = 'ty_id';
}