<?php

namespace app\index\model;

use think\Model;

class AuthGroupAccess extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected $pk='uid';
}